version: '3.7'

services:

  minio:
    container_name: minio_snsd
    image: quay.io/minio/minio:RELEASE.2023-02-27T18-10-45Z
    command: server /data --console-address ":9090"
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      - MINIO_CONFIG_ENV_FILE=/etc/conf/config.env
    volumes:
      - ${HOME}/minio/data:/data
      - ${HOME}/minio_scripts/deployment/snsd_docker/conf:/etc/conf
